/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_ui;



import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yulianto Pambudi
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public static Connection con;
    public static Statement st;
    public ResultSet rs;
    Koneksi db = new Koneksi();
   private DefaultTableModel model;
   String query2;
 
    public admin() {
        
                
        initComponents();
        this.model = new DefaultTableModel();
            tabelTayang.setModel(model);
            
            model.addColumn("Id_Tayang");
            model.addColumn("Id Tempat");
            model.addColumn("Id Jadwal");
            model.addColumn("Judul Film");
            model.addColumn("Studio");
            model.addColumn("Kursi");
            model.addColumn("Tanggal");
            model.addColumn("Waktu");
            model.addColumn("Harga");
        
            GetDataJadwal();
            GetListTempat();
            GetListJadwal();
            GetListFilm();
            GetListKursi();
            GetListStudio();
            GetListTarif();
            GetListTempat();
            GetListbioskop();
            GetListTanggal();
            GetListWaktu();
            setLocationRelativeTo(null);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameTayang = new javax.swing.JFrame();
        panelTayang1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboTempat = new javax.swing.JComboBox();
        comboJadwal = new javax.swing.JComboBox();
        comboFilm = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        simpanTayang = new javax.swing.JButton();
        fieldTayang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTayang = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        FrameFilm = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldIDFilm = new javax.swing.JTextField();
        fieldNamaFilm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        simpanFilm = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        FrameJadwal = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fieldJadwal = new javax.swing.JTextField();
        comboWaktu = new javax.swing.JComboBox();
        comboTarif = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        simpanJadwal = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        comboTanggal = new javax.swing.JComboBox();
        FrameTempat = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        comboBioskop = new javax.swing.JComboBox();
        comboStudio = new javax.swing.JComboBox();
        comboKursi = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        simpanTempat = new javax.swing.JButton();
        fieldIDTempat = new javax.swing.JTextField();
        panelTayang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        FrameTayang.setLocationByPlatform(true);
        FrameTayang.setUndecorated(true);
        FrameTayang.setResizable(false);

        jLabel6.setText("Id Tayang");

        jLabel7.setText("Id Tempat");

        jLabel8.setText("Id Jadwal ");

        jLabel9.setText("Id film");

        comboTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTempatActionPerformed(evt);
            }
        });

        comboJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJadwalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Menambah data ke Tabel Tayang");

        simpanTayang.setText("Simpan");
        simpanTayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTayangActionPerformed(evt);
            }
        });

        fieldTayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTayangActionPerformed(evt);
            }
        });

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelTayang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTayang);

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTayang1Layout = new javax.swing.GroupLayout(panelTayang1);
        panelTayang1.setLayout(panelTayang1Layout);
        panelTayang1Layout.setHorizontalGroup(
            panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTayang1Layout.createSequentialGroup()
                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTayang1Layout.createSequentialGroup()
                        .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTayang1Layout.createSequentialGroup()
                                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jButton1))
                                .addGap(102, 102, 102)
                                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTempat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboFilm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldTayang)
                                    .addComponent(simpanTayang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelTayang1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)))
                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTayang1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTayang1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(52, 52, 52))))
        );
        panelTayang1Layout.setVerticalGroup(
            panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTayang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(79, 79, 79)
                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(comboFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(panelTayang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanTayang)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(85, 85, 85))
            .addGroup(panelTayang1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameTayangLayout = new javax.swing.GroupLayout(FrameTayang.getContentPane());
        FrameTayang.getContentPane().setLayout(FrameTayangLayout);
        FrameTayangLayout.setHorizontalGroup(
            FrameTayangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTayang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameTayangLayout.setVerticalGroup(
            FrameTayangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTayang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FrameFilm.setLocationByPlatform(true);
        FrameFilm.setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 391));

        jLabel11.setText("ID Film");

        jLabel12.setText("Nama Film");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Memasukkan Film");

        simpanFilm.setText("Simpan");
        simpanFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanFilmActionPerformed(evt);
            }
        });

        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simpanFilm))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldIDFilm)
                                    .addComponent(fieldNamaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel13)
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldIDFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fieldNamaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanFilm)
                    .addComponent(jButton4))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameFilmLayout = new javax.swing.GroupLayout(FrameFilm.getContentPane());
        FrameFilm.getContentPane().setLayout(FrameFilmLayout);
        FrameFilmLayout.setHorizontalGroup(
            FrameFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        FrameFilmLayout.setVerticalGroup(
            FrameFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        FrameJadwal.setUndecorated(true);

        jLabel14.setText("ID Jadwal");

        jLabel15.setText("Tanggal");

        jLabel16.setText("ID Waktu");

        jLabel17.setText("ID Tarif");

        comboWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWaktuActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Memasukkan Data Jadwal Baru");

        simpanJadwal.setText("Simpan");
        simpanJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanJadwalActionPerformed(evt);
            }
        });

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(162, 162, 162))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(174, 174, 174)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(simpanJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(fieldJadwal)
                            .addComponent(comboWaktu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTarif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTanggal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel18)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fieldJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(comboTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(comboWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(comboTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanJadwal)
                    .addComponent(jButton5))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameJadwalLayout = new javax.swing.GroupLayout(FrameJadwal.getContentPane());
        FrameJadwal.getContentPane().setLayout(FrameJadwalLayout);
        FrameJadwalLayout.setHorizontalGroup(
            FrameJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameJadwalLayout.setVerticalGroup(
            FrameJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FrameTempat.setUndecorated(true);

        jLabel19.setText("ID Tempat");

        jLabel20.setText("ID Bioskop");

        jLabel21.setText("ID Studio");

        jLabel22.setText("ID Kursi");

        comboStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStudioActionPerformed(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Memasukkan Data Tempat");

        jButton6.setText("Kembali");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        simpanTempat.setText("Simpan");
        simpanTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTempatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton6)))
                .addGap(153, 153, 153)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboBioskop, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboStudio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboKursi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpanTempat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(fieldIDTempat))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel23)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(fieldIDTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(comboBioskop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(comboStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(comboKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanTempat)
                    .addComponent(jButton6))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout FrameTempatLayout = new javax.swing.GroupLayout(FrameTempat.getContentPane());
        FrameTempat.getContentPane().setLayout(FrameTempatLayout);
        FrameTempatLayout.setHorizontalGroup(
            FrameTempatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameTempatLayout.setVerticalGroup(
            FrameTempatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        jButton7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton7.setText("Film");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton8.setText("Jadwal");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton9.setText("Tayang");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton10.setText("Tempat");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Logout_Rounded_Up_64px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTayangLayout = new javax.swing.GroupLayout(panelTayang);
        panelTayang.setLayout(panelTayangLayout);
        panelTayangLayout.setHorizontalGroup(
            panelTayangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTayangLayout.createSequentialGroup()
                .addGroup(panelTayangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTayangLayout.createSequentialGroup()
                        .addGroup(panelTayangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTayangLayout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addGroup(panelTayangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelTayangLayout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 222, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTayangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        panelTayangLayout.setVerticalGroup(
            panelTayangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTayangLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTayang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void GetListTempat(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM tempat";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_tempat = rs.getString("id_tempat");
                comboTempat.addItem(id_tempat);
                //comboTempat2.addItem(id_tempat);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
     public void GetListJadwal(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM jadwal";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_jadwal = rs.getString("id_jadwal");
                comboJadwal.addItem(id_jadwal);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
      public void GetListFilm(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM film";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_film = rs.getString("id_film");
                comboFilm.addItem(id_film);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
      
      public void GetListWaktu(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM waktu";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_waktu = rs.getString("id_waktu");
                comboWaktu.addItem(id_waktu);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
      public void GetListTarif(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM tarif";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_tarif = rs.getString("id_tarif");
                comboTarif.addItem(id_tarif);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
      public void GetListKursi(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM kursi";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_kursi = rs.getString("id_kursi");
                comboKursi.addItem(id_kursi);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
      public void GetListbioskop(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM bioskop";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_bioskop = rs.getString("id_bioskop");
                comboBioskop.addItem(id_bioskop);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }public void GetListStudio(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM studio";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_studio = rs.getString("id_studio");
                comboStudio.addItem(id_studio);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void GetListTanggal(){
        String query;
       
        try{
            con = db.con;
            st = (Statement) con.createStatement();
            query = "SELECT * FROM tanggal";
            
            rs = st.executeQuery(query);
            
            while(rs.next()){
                String id_tanggal = rs.getString("tanggal");
                comboTanggal.addItem(id_tanggal);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void comboJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJadwalActionPerformed

    private void simpanTayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTayangActionPerformed
        // TODO add your handling code here:
        
        String ambilTempat = (String)comboTempat.getSelectedItem();
        String ambilJadwal = (String)comboJadwal.getSelectedItem();
        String ambilFilm = (String)comboFilm.getSelectedItem();
        String id_tayang = fieldTayang.getText();
        //System.out.println(fieldTayang.getText()+ambilTempat+ambilJadwal+ambilFilm);
        try{
            String query;
            con = db.con;
            st =(Statement) con.createStatement();

            query = "INSERT INTO tayang (`id_tayang`, `id_tempat`, `id_jadwal`, `id_film`) Values"+
            "('"+id_tayang+"','"+ambilTempat+"','"+ambilJadwal+"','"+ambilFilm+"')";

            st.executeUpdate(query);
            System.out.println("Input Berhasil");
            JOptionPane.showMessageDialog(null, "BERHASIL!!!!!!!!");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "SALAH");
        }

    }//GEN-LAST:event_simpanTayangActionPerformed

    private void fieldTayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTayangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTayangActionPerformed

    private void comboTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTempatActionPerformed

    private void comboWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboWaktuActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
        FrameFilm.setVisible(true);
        FrameFilm.setLocationRelativeTo(null);
        FrameFilm.setSize(556, 376);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dispose();
        FrameJadwal.setVisible(true);
        FrameJadwal.setLocationRelativeTo(this);
        FrameJadwal.setSize(550, 377);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        dispose();   
        FrameTayang.setVisible(true);
        FrameTayang.setSize(966, 455);
        FrameTayang.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        dispose();
        FrameTempat.setVisible(true);
        FrameTempat.setLocationRelativeTo(this);
        FrameTempat.setSize(557, 341);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handlingode here:
       
        admin adm = new admin();
        adm.dispose();
        FrameTayang.dispose();
        FrameFilm.dispose();
        FrameJadwal.dispose();
        FrameTempat.dispose();
        adm.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        admin adm = new admin();
        adm.dispose();
        FrameTayang.dispose();
        FrameFilm.dispose();
        FrameJadwal.dispose();
        FrameTempat.dispose();
        adm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        admin adm = new admin();
        adm.dispose();
        FrameTayang.dispose();
        FrameFilm.dispose();
        FrameJadwal.dispose();
        FrameTempat.dispose();
        adm.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void comboStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStudioActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        admin adm = new admin();
        adm.dispose();
        FrameTayang.dispose();
        FrameFilm.dispose();
        FrameJadwal.dispose();
        FrameTempat.dispose();
        adm.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void simpanFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanFilmActionPerformed
        // TODO add your handling code here:
        try{
            String query;
            con = db.con;
            st =(Statement) con.createStatement();
               
            String id_film = fieldIDFilm.getText();
            String nama_film = fieldNamaFilm.getText();
            query= "INSERT INTO film(`id_film`, `judul_film`) Values"+
            "('"+id_film+"','"+nama_film+"')";

            st.executeUpdate(query);
            System.out.println("Input Berhasil");
            JOptionPane.showMessageDialog(null, "BERHASIL!!!!!!!!");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "SALAH");
        }
    }//GEN-LAST:event_simpanFilmActionPerformed

    private void simpanJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanJadwalActionPerformed
        // TODO add your handling code here:
        String ambilWaktu = (String)comboWaktu.getSelectedItem();
        String ambilTarif = (String)comboTarif.getSelectedItem();
        String ambilTanggal =(String)comboTanggal.getSelectedItem();
        String ambilJadwal = fieldJadwal.getText();
               

        try{
            String query;
            con = db.con;
            st =(Statement) con.createStatement();

            query = "INSERT INTO jadwal (`id_jadwal`,`tanggal`, `id_waktu`, `id_tarif`) Values"+
            "('"+ambilJadwal+"','"+ambilTanggal+"','"+ambilWaktu+"','"+ambilTarif+"')";
            
            //System.out.println(ambilJadwal+ambilTanggal+ambilWaktu+ambilTarif);
            st.executeUpdate(query);
            System.out.println("Input Berhasil");
            JOptionPane.showMessageDialog(null, "BERHASIL!!!!!!!!");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "SALAH");
        }
    }//GEN-LAST:event_simpanJadwalActionPerformed

    private void simpanTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTempatActionPerformed
        // TODO add your handling code here:
        String ambilTempat = fieldIDTempat.getText();
        String ambilBioskop = (String)comboBioskop.getSelectedItem();
        String ambilStudio = (String)comboStudio.getSelectedItem();
        String ambilKursi = (String) comboKursi.getSelectedItem();
               
        try{
            String query;
            con = db.con;
            st =(Statement) con.createStatement();

            query = "INSERT INTO tempat (`id_tempat`,`id_bioskop`, `id_studio`, `id_kursi`) Values"+
            "('"+ambilTempat+"','"+ambilBioskop+"','"+ambilStudio+"','"+ambilKursi+"')";
            
            System.out.println(ambilTempat+ambilBioskop+ambilStudio+ambilKursi);
            st.executeUpdate(query);
            System.out.println("Input Berhasil");
            JOptionPane.showMessageDialog(null, "BERHASIL!!!!!!!!");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "SALAH");
        }
    }//GEN-LAST:event_simpanTempatActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    public void GetDataJadwal(){
       
        try{
            
            con = db.con;
            
            query2 = "SELECT distinct tayang.id_tayang ,tayang.id_tempat, tayang.id_jadwal, film.judul_film, studio.nama_studio,kursi.nama_kursi, \n"
                    +"tanggal.tanggal, waktu.waktu_mulai,tarif.harga\n"
                    +"from film, studio, kursi, tanggal, waktu, tarif,tempat,jadwal,tayang,pesan\n"
                    +"where tayang.id_film = film.id_film and tempat.id_kursi = kursi.id_kursi and \n"
                    +"tempat.id_studio = studio.id_studio and\n"
                    +"jadwal.tanggal = tanggal.tanggal and jadwal.id_waktu = waktu.id_waktu and\n"
                    +"jadwal.id_tarif = tarif.id_tarif and tayang.id_tempat = tempat.id_tempat and\n"
                    +"tayang.id_jadwal = jadwal.id_jadwal";
            
            st = (Statement) con.createStatement();
            rs = st.executeQuery(query2);
            
            while(rs.next()){
                Object[] obj = new Object[9];
                obj[0] = rs.getString("id_tayang");
                obj[1] = rs.getString ("id_tempat");
                obj[2] = rs.getString("id_jadwal");
                obj[3] = rs.getString("judul_film");
                obj[4] = rs.getString("nama_studio");
                obj[5] = rs.getString("nama_kursi");
                obj[6] = rs.getString("tanggal");
                obj[7] = rs.getString("waktu_mulai");
                obj[8] = rs.getString("harga");
                
                model.addRow(obj);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "HAPUS DATA?", "HAPUS DATA", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            int i = tabelTayang.getSelectedRow();
            String id_tayang = tabelTayang.getValueAt(i, 0).toString();
            try{
                String query;
                con = db.con;
                st = (Statement) con.createStatement();
                query = "delete from tayang where id_tayang = '"+id_tayang+"'";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "BERHASIL DI HAPUS");
                DelTable();
                GetDataJadwal();
                
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
       }
           
                   
       }
    }//GEN-LAST:event_jButton2ActionPerformed
public void DelTable(){
        int baris = model.getRowCount();
        for(int i=0 ; i<baris ; i++){
            model.removeRow(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameFilm;
    private javax.swing.JFrame FrameJadwal;
    private javax.swing.JFrame FrameTayang;
    private javax.swing.JFrame FrameTempat;
    private javax.swing.JComboBox comboBioskop;
    private javax.swing.JComboBox comboFilm;
    private javax.swing.JComboBox comboJadwal;
    private javax.swing.JComboBox comboKursi;
    private javax.swing.JComboBox comboStudio;
    private javax.swing.JComboBox comboTanggal;
    private javax.swing.JComboBox comboTarif;
    private javax.swing.JComboBox comboTempat;
    private javax.swing.JComboBox comboWaktu;
    private javax.swing.JTextField fieldIDFilm;
    private javax.swing.JTextField fieldIDTempat;
    private javax.swing.JTextField fieldJadwal;
    private javax.swing.JTextField fieldNamaFilm;
    private javax.swing.JTextField fieldTayang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTayang;
    private javax.swing.JPanel panelTayang1;
    private javax.swing.JButton simpanFilm;
    private javax.swing.JButton simpanJadwal;
    private javax.swing.JButton simpanTayang;
    private javax.swing.JButton simpanTempat;
    private javax.swing.JTable tabelTayang;
    // End of variables declaration//GEN-END:variables
}
