/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_ui;

import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import com.mysql.jdbc.Statement;
import javax.swing.table.*;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Mclay
 */
public class RiwayatPemesanan extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    String query;
    Koneksi db = new Koneksi();
    private DefaultTableModel model;
    String user = LoginForm.getPengguna();

    /**
     * Creates new form RiwayatPemesanan
     */
    int xMouse;
    int yMouse;
    public RiwayatPemesanan() {
        initComponents();
        this.model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tblriwayat.setModel(model);
        model.addColumn("Id Pemesanan");
        model.addColumn("Film");
        model.addColumn("Studio");
        model.addColumn("Kursi");
        model.addColumn("Tanggal Tayang");
        model.addColumn("Waktu Tayang");
        model.addColumn("Harga");
        model.addColumn("Tanggal Pemesanan");
        model.addColumn("Status");
        model.addColumn("Kasir");
        GetDataRiwayat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblriwayat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        kGradientPanel1.setEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setStartColor(new java.awt.Color(204, 0, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALTO BIOSKOP");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(520, 0, 190, 30);

        kGradientPanel2.setEndColor(new java.awt.Color(0, 204, 255));

        kGradientPanel4.setEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel4.setStartColor(new java.awt.Color(255, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RIWAYAT");
        kGradientPanel4.add(jLabel1);
        jLabel1.setBounds(10, 50, 130, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PEMESANAN");
        kGradientPanel4.add(jLabel2);
        jLabel2.setBounds(10, 90, 160, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIKET");
        kGradientPanel4.add(jLabel3);
        jLabel3.setBounds(10, 140, 80, 40);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_50px_1.png"))); // NOI18N
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        kGradientPanel4.add(jLabel36);
        jLabel36.setBounds(0, 370, 70, 60);

        kGradientPanel2.add(kGradientPanel4);
        kGradientPanel4.setBounds(-1, -1, 220, 430);

        tblriwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblriwayat.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tblriwayat);

        kGradientPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(240, 20, 930, 402);

        kGradientPanel1.add(kGradientPanel2);
        kGradientPanel2.setBounds(10, 40, 1180, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1199, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void GetDataRiwayat(){
        try{
            con = db.con;
            query = "select distinct pesan.id_pesan, film.judul_film, studio.nama_studio, kursi.nama_kursi, \n"
                    + "tanggal.tanggal, waktu.waktu_mulai, tarif.harga, pesan.tanggal_pemesanan,"
                    + " pesan.status, pesan.username_kasir \n"
                    + "from film, studio, kursi, tanggal, waktu, tarif, "
                    + "tempat, jadwal, tayang, pesan, pengguna, kasir\n"
                    + "where pesan.id_tayang = tayang.id_tayang and tayang.id_film = film.id_film and \n"
                    + "tempat.id_studio = studio.id_studio and tempat.id_kursi = kursi.id_kursi and \n"
                    + "jadwal.tanggal = tanggal.tanggal and jadwal.id_waktu = waktu.id_waktu and \n"
                    + "jadwal.id_tarif = tarif.id_tarif and tayang.id_tempat = tempat.id_tempat and \n"
                    + "tayang.id_jadwal = jadwal.id_jadwal and pesan.username = pengguna.username "
                    + "and pesan.username = '"+user+"' order by pesan.tanggal_pemesanan";
            st = (Statement) con.createStatement();
            rs = st.executeQuery(query);
            
            while(rs.next()){
                Object[] obj = new Object[10];
                obj[0] = rs.getString("id_pesan");
                obj[1] = rs.getString("judul_film");
                obj[2] = rs.getString("nama_studio");
                obj[3] = rs.getString("nama_kursi");
                obj[4] = rs.getString("tanggal");
                obj[5] = rs.getString("waktu_mulai");
                obj[6] = rs.getString("harga");
                obj[7] = rs.getString("tanggal_pemesanan");
                obj[8] = rs.getString("status");
                obj[9] = rs.getString("username_kasir");
                
                
                model.addRow(obj);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked

        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel36MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JTable tblriwayat;
    // End of variables declaration//GEN-END:variables
}
